# This is the main configuration file for the application.
# https://www.playframework.com/documentation/latest/ConfigFile


play.filters.hosts {
  # Allow requests to example.com, its subdomains, and localhost:9001.
  allowed = ["0.0.0.0:9000", "localhost:9000"]
}

play.filters.enabled += play.filters.cors.CORSFilter

play.modules.enabled += "tasks.InitTasksModule"

file{
  league_file_name = "LeagueFile.txt"
  match_file_name = "MatchFile.txt"
}


# API prefix to be used for all API routes
apiPrefix = "api"

delayStartUI = 30000